creditflow {
  http {
    host = "0.0.0.0"
    port = 8082
  }
  db {
    url = "jdbc:postgresql://localhost:5432/transactions_db"
    user = "creditflow"
    password = "creditflow"
  }
  kafka {
    bootstrap-servers = "localhost:9092"
    client-id = "transaction-service"
  }
}
